In [2]:
# Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
 #select a single element
simple_indexing = arr[6]

print("Simple Indexing:", simple_indexing)

# select multiple elements
fancy_indexing = arr[[1, 2, 5, 7]]

print("Fancy Indexing:",fancy_indexing)

Simple Indexing: 7
Fancy Indexing: [2 3 6 8]


In [3]:
# Q2. Execute the 2D array Slicing.
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print("~~~~~~~~~~~")
print(arr[0, 1:3])
print("~~~~~~~~~~~")
print(arr[1, 1:4])
print("~~~~~~~~~~~")
print(arr[0:2, 2:5])
print("~~~~~~~~~~~")
print(arr[0:1, 2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
~~~~~~~~~~~
[2 3]
~~~~~~~~~~~
[7 8 9]
~~~~~~~~~~~
[[ 3  4  5]
 [ 8  9 10]]
~~~~~~~~~~~
[3]


In [32]:


# Q3. Create the 5-Dimensional arrays using ‘ndmin’.
arr = np.array([[1, 2, 3, 4],[5,6,7,8]], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]
    [5 6 7 8]]]]]
number of dimensions : 5


In [28]:

# Q4. Reshape the array from 1-D to 2-D array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
# Q5. Perform the Stack functions in Numpy arrays – Stack()

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
#  hstack()

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [33]:
# vstack()

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [29]:
# dstack().
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [9]:
# Q6. Perform the searchsort method in Numpy array.
import numpy as np

arr = np.array([6, 8, 9,7])

x = np.searchsorted(arr, 7,side='left')

print(x)

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [5,7])


print(x)

1
[2 3]


In [10]:

# Q7. Create Numpy Structured array using your domain features.


a = np.array([('Think Like A monk', 'Jay Shetty', 2019), ('BuildConfidence', 'Daniel Chadwick', 2000), ('Learn Programmin', 'Maria', 39.0)],
       dtype=[('PodcastName', (np.str_, 10)), ('age', np.int32), ('weight', np.float64)])

print(a)

[('Kim', 20, 21.) ('Sam', 14, 29.) ('John', 17, 39.)]


In [14]:
# Q8. Create Data frame using List and Dictionary.
import pandas

mydataset = {
  'Languages': ["C", "C++", "Java", "Python"],
  'Year': [1972, 1979, 1996, 1991]
}

myvar = pandas.DataFrame(mydataset) # Creating Dataframe from Dictionary
print(myvar)

mylist = [1972, 1979, 1996, 1991]
myvar = pd.DataFrame(mylist, index =['a', 'b', 'c', 'd'],
                                              columns =['Years']) # Dataframe using list with indexing
print(myvar)


  Languages  Year
0         C  1972
1       C++  1979
2      Java  1996
3    Python  1991
  Languages  Year
0         C  1972
1       C++  1979
2      Java  1996
3    Python  1991


In [30]:
# Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the
# missing data from the dataset.
# • isnull()
# • notnull()
# • dropna()
# • fillna()
# • replace()
# • interpolate()
mydataset = {
  'Languages': ["English", "Hindi", "French"],
  'Podcast-Name': ["Think like a monk", "WhatsUp sister", "learn Programming with fun"],
  'Host':["Jay Shetty","Daniel Chadwick","Maria"],
  'Year-of-release':[2019,2000,2020]
}

myvar = pandas.DataFrame(mydataset) # Creating Dataframe from Dictionary with domain-online podcast
print(myvar)
myvar.isnull()
myvar.notnull()
myvar.dropna()
# myvar.fillna()



  Languages                Podcast-Name             Host  Year-of-release
0   English           Think like a monk       Jay Shetty             2019
1     Hindi              WhatsUp sister  Daniel Chadwick             2000
2    French  learn Programming with fun            Maria             2020


Languages                Podcast-Name             Host  Year-of-release
0   English           Think like a monk       Jay Shetty             2019
1     Hindi              WhatsUp sister  Daniel Chadwick             2000
2    French  learn Programming with fun            Maria             2020

In [31]:
myvar.replace()
myvar.interpolate()

/var/folders/2l/81m_7r0506l5xwcgb2gp407h0000gn/T/ipykernel_1665/3686585549.py:1: FutureWarning: DataFrame.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  myvar.replace()
/var/folders/2l/81m_7r0506l5xwcgb2gp407h0000gn/T/ipykernel_1665/3686585549.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  myvar.interpolate()


Languages                Podcast-Name             Host  Year-of-release
0   English           Think like a monk       Jay Shetty             2019
1     Hindi              WhatsUp sister  Daniel Chadwick             2000
2    French  learn Programming with fun            Maria             2020

In [34]:
# Q10. Perform the Hierarchical Indexing in the above created dataset.
import pandas as pd
import numpy as np

# Create a DataFrame with synthetic student data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [20, 21, np.nan, 22, 23],
    'Gender': ['Female', 'Male', 'Male', 'Male', 'Female'],
    'Score': [90, np.nan, 75, np.nan, 88]
}

# Create a MultiIndex DataFrame with two levels of indexing
arrays = [
    ['Class A', 'Class A', 'Class B', 'Class B', 'Class C'],
    ['Student 1', 'Student 2', 'Student 1', 'Student 2', 'Student 1']
]

index = pd.MultiIndex.from_arrays(arrays, names=('Class', 'Student'))

df = pd.DataFrame(data, index=index)

# Display the DataFrame with hierarchical indexing
print("DataFrame with Hierarchical Indexing:")
print(df)

DataFrame with Hierarchical Indexing:
                      Name   Age  Gender  Score
Class   Student                                
Class A Student 1    Alice  20.0  Female   90.0
        Student 2      Bob  21.0    Male    NaN
Class B Student 1  Charlie   NaN    Male   75.0
        Student 2    David  22.0    Male    NaN
Class C Student 1      Eva  23.0  Female   88.0
